import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatCheckboxModule,
    MatGridListModule,
    MatListModule,
    MatToolbarModule,
    MatIconModule,
    MatPaginatorModule,
    MatTableModule,
    MatFormFieldModule,
    MatDialogModule,
    MatRadioModule,
    MatOptionModule,
    MatSelectModule,
    MatButtonToggleModule,
    MatInputModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatCardModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatExpansionModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatDatepickerModule,
    MatNativeDateModule, 
    MatTooltipModule,
    MatSortModule
} from '@angular/material';
import { FormsModule, ReactiveFormsModule, } from '@angular/forms'
import { MatMenuModule } from '@angular/material/menu';
@NgModule({
    imports: [MatButtonModule,
        MatButtonToggleModule,
        MatCheckboxModule,
        MatGridListModule,
        MatListModule,
        MatToolbarModule,
        MatIconModule,
        MatPaginatorModule,
        MatTableModule,
        MatFormFieldModule,
        MatDialogModule,
        FormsModule,
        MatRadioModule,
        MatOptionModule,
        MatSelectModule,
        MatInputModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatProgressBarModule,
        MatStepperModule,
        ReactiveFormsModule,
        MatAutocompleteModule,
        MatExpansionModule,
        MatTabsModule,
        MatProgressSpinnerModule,
        MatSidenavModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatChipsModule,
        MatTooltipModule, 
        MatSortModule,
        MatCheckboxModule,
        
    ],
    exports: [MatButtonModule,
        MatButtonToggleModule,
        MatCheckboxModule,
        MatGridListModule,
        MatListModule,
        MatToolbarModule,
        MatIconModule,
        MatPaginatorModule,
        MatTableModule,
        MatFormFieldModule,
        MatMenuModule,
        MatDialogModule,
        FormsModule,
        MatRadioModule,
        MatOptionModule,
        MatSelectModule,
        MatInputModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatProgressBarModule,
        MatCardModule,
        MatStepperModule,
        ReactiveFormsModule,
        MatAutocompleteModule,
        MatExpansionModule,
        MatTabsModule,
        MatProgressSpinnerModule,
        MatSidenavModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatChipsModule,
        MatTooltipModule
    ],
    providers: [],
})
export class MaterialModule { }